### ISSUE TITLE
TypeError: take() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by qamaheshkumar** [aaditagarwal/player_performance_predictor#11]
Traceback (most recent call last):
  File "run.py", line 76, in <module>
    res = player_performance(param,player_name,opposition,venue)
  File "D:\ML_Pred_Practice\player_performance_predictor\scripts\player_performance.py", line 146, in player_performance
    bat_gridresult_xgb = bat_gridsearch_xgb.fit(bat_features,bat_targets)

Example :
Enter the desired team: India
Enter the desired player_name: V Kohli
Enter the desired opposition: Australia
Enter the desired venue: Wankhede Stadium

**Comment by buddhika9** [comment]
Have you fix this error ??
